### PR TITLE
Update 3-3-play-with-this-page.md

### PR DESCRIPTION
**Pull request by karegapauline**
OLS2 cohort call practising pull request

### CODE REVIEW

**Comment by cassgvp** [comment]
Congrats on submitting your PR, @karegapauline ! Very glad you could catch up on the materials 😊

**Comment by cassgvp** [comment]
Hi @karegapauline , I would like to add a link to your GitHub profile next to where you submitted your name. Would this be ok? Feels like you should have some more visibility than simply your name!

**Comment by karegapauline** [comment]
Hi @cassgvp 
You made github seem so simple. Thanks :)
Yes you can add it. Thanks Cass

**Comment by cassgvp** [comment]
Yay! I'm so pleased! 

Github handle added! See commit cdc5ff9c1ac2fd1929185eb53ce14a26667f3dc5

**Pull request merged**
