### PR TITLE
Added name on line 4

### PR DESCRIPTION
**Pull request by natty2012**

### CODE REVIEW

**Comment by cassgvp** [comment]
Congratulations on submitting your PR to add your name @natty2012 ! I've move it to a different line as the list was updating, but you are there at item 14! Very well done getting through all the material yesterday!

**Comment by natty2012** [comment]
Thank you Cass, the tutorial you took us through yesterday was
really helpful & fun. Looking forward to working better on github

**Comment by cassgvp** [comment]
Hi @natty2012, I would like to add a link to your GitHub profile next to where you submitted your name. Would this be ok? Feels like you should have some more visibility than simply your name!

**Comment by natty2012** [comment]
Hi Cass, sure! that would be nice, thank you..will this help people see my
profile? :-)

**Pull request merged**
