### PR TITLE
Added an image

### PR DESCRIPTION
**Pull request by Jelioth**

### CODE REVIEW

**Comment by cassgvp** [comment]
Thank you for you beautiful picture!! 👍

**Comment by cassgvp** [comment]
Hi @Jelioth , I would like to add a link to your name and GitHub profile next to where you submitted your picture. Would this be ok? Feels like you should have some more visibility than simply your name!

**Comment by Jelioth** [comment]
Hi Cass, Yes sure. I am okay

**Comment by Jelioth** [comment]
Hi Cassandra, my apologies for not completing your name in the earlier
email.


Kind regards,
Jelioth Muthoni.

**Comment by cassgvp** [comment]
No problem! I received the notice anyway as I'm in the chain of comments :). Now added you in commit 596c9f2942ab0ed66c27067301d331977a824690

**Comment by Jelioth** [comment]
Awesome!
Thank you very much.

**Pull request merged**
